name: Fist
api: [3.0.0]
version: 1.0.0
main: FaizDev\fist\Main
author: FaizDev

commands:
  fist:
    description: §cF§1i§as§et§r §6Commands

permissions:
  fist.command.admin:
    description: Permission to allow use all fist commands