name: Fist
api: 4.0.0
version: 1.0.1
main: FaizDev\fist\Main
author: FaizDev

permissions:
  fist.command.admin:
    default: op 
  fist.command.join:
    default: true
  fist.command.quit:
    default: true
